[[redirects]]
from = “/*”
to = “/index.html”
status = 200

[[redirects]]
  from = “/inventory/*”
  to = “https://clients.automanager.com/3384c1d0d56a40e6a9aaf738622b81cf/inventory.xml?ID=57885f7924&Features=1&Photos=1"
  status = 200
[[redirects]]
  from = “/*”
  to = “/index.html”
  status = 200