[[redirects]]
from = “/*”
to = “/index.html”
status = 200

[[redirects]]
  from = “/inventory/*”
  to = “/inventory.xml?ID=57885f7924&Features=1&Photos=1"
  status = 200
[[redirects]]
  from = “/*”
  to = “/index.html”
  status = 200